export async function GET() {
  const URL = process.env.NEXT_PUBLIC_URL || 'https://hooklab.ai';
  
  const manifest = {
    "accountAssociation": {
      "header": "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4NUVCQTAzM0YxRDE0NTgzYjg2ZDFhMDEzMTNGNDdEM0RFNzY2Mjc1MCJ9",
      "payload": "eyJkb21haW4iOiJtaW5pa2l0LXRlc3QtaG9va2xhYmFpLnZlcmNlbC5hcHAifQ",
      "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAYm7mZxSiGVERKY8m0gClyOg9WwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBKmygyi_1qOfmWPUjDjZZ-LfoXI7d_dhtDCA7QZwHidZRFy1ju9Kdu5lRgWAcAYNmDL_EZLWkf2v_pK8YJgrgYRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI"
    },
    miniapp: {
      version: "1",
      name: "HookLab AI",
      homeUrl: URL,
      iconUrl: `${URL}/logo_hooklab.png`,
      splashImageUrl: `${URL}/logo_hooklab.png`,
      splashBackgroundColor: "#000000",
      webhookUrl: `${URL}/api/webhook`,
      subtitle: "Viral Hooks in Seconds",
      description: "Platform AI Agent yang menghasilkan viral hooks dan visual menarik untuk sosial media.",
      screenshotUrls: [
        `${URL}/screenshot1.png`
      ],
      primaryCategory: "social",
      tags: ["ai", "social", "farcaster", "base"],
      heroImageUrl: `${URL}/og.png`,
      tagline: "Generate, Hook, Viral.",
      ogTitle: "HookLab AI",
      ogDescription: "Generate viral hooks with AI",
      ogImageUrl: `${URL}/og.png`,
      noindex: true
    }
  };

  return Response.json(manifest);
}
